### ISSUE TITLE
Is this project abandonded?

### ISSUE THREAD

**Issue by tjdevries** [ThePrimeagen/git-worktree.nvim#1]
Just not seeing a lot of movement on the project at the moment.

Thanks!

**Comment by frandsoh** [comment]
The latest commit was at least 17 hours ago. I think it's safe to say the project is abandoned.

Someone ought to fork it and continue the legacy.

Telescopic Johnson (@tjdevries), are you up for the challenge?

It would be a shame to see a project like this come to a stand still 🥺

**Comment by ThePrimeagen** [comment]
Neither of you two deserve this project.  When I am going to talk to Jack Dorsey and see if we can you two banned from twitter, as I assume this is where the harassment planning is taking place.

https://www.youtube.com/watch?v=vmX0MCf1fKs

**Comment by kuator** [comment]
TJ: The CEO of harassment

**Comment by bfredl** [comment]
is this recommended over neogit? asking for a friend.

**Comment by ThePrimeagen** [comment]
sowwy, jokes over :)
