### ISSUE TITLE
errors during set_branch

### ISSUE THREAD

**Issue by polarmutex** [ThePrimeagen/git-worktree.nvim#11]
not sure if I am doing something wrong or misunderstanding something

steps I am doing
1. git clone --bare <repo url>
2. cd <repo.git>
3. nvim
4. :lua require('git-worktree').create_worktree("master", "origin/master")

it creates the worktree but I get an error on set_branch saying the requested upstream branch "origin/master" does not exist

thoughts on what is happening?

**Comment by polarmutex** [comment]
looking at create_worktree a little closer, is there a reason we are not calling "git worktree add"?

**Comment by ThePrimeagen** [comment]
@polarmutex we are calling worktree add... Perhaps I am missing something.  But you are right.  That is a problem. 


It seems to happen if you don't have _2 remotes_.  If you have an upstream and an origin, this works.  But if you don't have an upstream, you have to use JUST `master`

I think we could fix this.

**Comment by ThePrimeagen** [comment]
What would be a good solution to this?  If we fail to set branch we print out error, but not stop the process?

**Comment by polarmutex** [comment]
PR fixed this issue
