### ISSUE TITLE
folder structure: cant find dir in cdpath

### ISSUE THREAD

**Issue by argapost** [ThePrimeagen/git-worktree.nvim#14]
Just started to use git-worktree so noob here.

If my folder structure is the following:
```
project/
    |__ master
             |__.git/
             |__code.py
    |__ test
            |__code.py
```
and for example, I am in the test worktree and I call switch to master, it fails because it looks for project/test/master whereas I want to look for project/master. 

Is this possible?

**Comment by polarmutex** [comment]
right now this plugin assumes you have a bare repo (git clone --bare <repo>) with the worktree in folders in that folder

project(bare)/
    |   (git repo root) 
    |___master
               |___code.py
           test
               |___code.py

On the project structure you presented, I think prime is interested in trying to support (that was the same structure I started with  too) but right now it is not supported

**Comment by ThePrimeagen** [comment]
I am very interested in properly supporting git worktrees in any working use case! 

I just haven't really explored other ways to do this.  Thanks so much for the issue.  @argapost could you give me your exact checkout / worktree executions and how you get to where you are.  There are _lots of assumptions_ in this plugin currently.

**Comment by polarmutex** [comment]
based on his folder structure,

1. git clone <repo>   // clones the master branch into a folder with a ".git" folder
2. cd <repo> 
3. git worktree add ../test test  // creates a worktree folder at the same level as the git repo

**Comment by argapost** [comment]
Thanks for the quick response! I understand that this is a very new project, so no worries. I will try @polarmutex suggestion with git clone --bare.

This is what I am trying:

1. ` mkdir project; cd project` ! in the project dir there is no .git
2. `git clone repo master` ! this clones the repo into a new directory called master
3.  ` cd master `
4.  `git add worktree ../test` ! to create a test branch inside the project dir but outside of master

I don't know if that helps.

**Comment by ThePrimeagen** [comment]
Goodness gracious!  I totally get this.  Ok, yeah, this definitely assumes bare repo.  I'll have to figure out how to determine "where" people put their repos.  I don't know how queryable repos are.

My guess is this, there is going to have to be a configuration that is required for this.  This is also the easiest solution.  Simply use case would be, based on the path and your configuration for that path, determines how to check out / where to checkout.

```lua
Worktree.setup({
    ["$HOME/path/to/repo"]: { bare: true }, -- assumes polar/my style (can be default behavior)
    ["$HOME/path/to/repo-2"]: { bare: false, root_repo: "master", worktree_dir: "." } -- assumes that root_repo relative to path is where the master git checkout is, worktree_dir where will be the checkout directory should be
})
```

Thoughts?
})

**Comment by polarmutex** [comment]
"git worktree list" does show the full path to the repos

with my path PR that was just merged, should get us closer to supporting this (you would need to call switch_worktree with the relative path to the folder from the root) 

I will test here soon

**Comment by argapost** [comment]
I liked the idea of a config where you choose the root_dir etc. if it is easy to implement.

when you git clone --bare you have all the .git/ files in the same directory with the worktree folders, right? 
With my structure, they are hidden within the project/master/.git/

**Comment by polarmutex** [comment]
i think we can get this without a config, let me look at this today

**Comment by ThePrimeagen** [comment]
I would prefer to avoid configuration.  One thing to think of polar is identifying _where to checkout new branches_.  With this plugin currently, if you open vim _within a worktree_ you will checkout your next worktree in that directory (fail).

That is why I was leaning towards a config, but if you can get this information from git, i'll be happy beyond belief!

**Comment by polarmutex** [comment]
first problem is that plenary's make_relative function does not handle going up in the filetree (because it clearly is abandoned)

so we either need to do the following 
- add that functionality to plenary
- make it so that the public api converts the relative path to an absolute one to make calls to has_worktree and others like it 
- make all the api calls use absolute paths
- go the config file route

I really do not like option 3,  thoughts?

**Comment by ThePrimeagen** [comment]
I feel like I could help with the plenary pr for making pathing better.  I ran into this earlier.

Path:new({"/foo/bar/baz", ".."}) == "/foo/bar/baz/.." which sucks and I could use it in other projects.  I am streaming tonight, how about I try to get a PR into that off the rip?

Also, what is your favorite option?  I would prefer to have the _best_ solution, but I am also super ok with a hack solution.

I do like the config option in the sense that you could specify things in _ANY_ way you want.  It really allows for us to have a default behavior, bare repos, anything else requires you to go ham.

**Comment by polarmutex** [comment]
just thinking through it. if plenary was fixed that would be the best. I do not see any road blocks to just using relative path to use for switching or creating worktrees

Plenary fix:
Lets say you have the following structure:
/project/master
/project/test

the problem i am running into is in the has_worktree function. The plugin calls "git worktree list" which returns absolute paths of all the worktrees. If you pass in a relative path up a level in the filetree (ex "../test"). It does a string compare between "/project/test" (what git worktree list returns) and "/project/master/../test" (what has_worktree puts togather). 

the plenary normalize function should fix the path but it calls make_relative that does not handle paths up in the tree.

hope that makes sense
