### ISSUE TITLE
[Configuration] Make ":Ex path" configurable

### ISSUE THREAD

**Issue by mrossinek** [ThePrimeagen/git-worktree.nvim#33]
It would be great if the user could configure the command which gets executed upon `update_on_change`.
Personally, I used to have `netrw` disabled and instead use [vim-dirvish](https://github.com/justinmk/vim-dirvish). This would be an easy fix if one could specify a setup-option (say e.g. `update_on_change_command`) and a user could exchange `:Ex` with `:Dirvish`. However, once we make this configurable one could even allow any vim-command (or even any lua function) to be given here. Right now, I am thinking that something like `:Telescope git_files` might be even cooler :thinking: 

I am happy to open a PR for this but wanted to get some input first.
- would a simple string command-option be enough?
- or do you think we need a lua function as the configurable option, such that we can also handle `path` being passed into it?
- actually on second though, why do we need to pass `path` to it? Isn't simply `:Ex` enough?

**Comment by mrossinek** [comment]
This would be the most basic patch I came up with:
```patch
diff --git a/lua/git-worktree/init.lua b/lua/git-worktree/init.lua
index ee704e8..d16472b 100644
--- a/lua/git-worktree/init.lua
+++ b/lua/git-worktree/init.lua
@@ -14,7 +14,7 @@ local function on_tree_change_handler(op, path, _) -- _ = upstream
         if op == Enum.Operations.Switch then
             local changed = M.update_current_buffer()
             if not changed then
-                vim.cmd(string.format(":Ex %s", M.get_worktree_path(path)))
+                vim.cmd(M._config.update_on_change_command)
             end
         end
     end
@@ -382,6 +382,7 @@ M.setup = function(config)
     config = config or {}
     M._config = vim.tbl_deep_extend("force", {
         update_on_change = true,
+        update_on_change_command = ":Ex",
         clearjumps_on_change = true,
         -- should this default to true or false?
         autopush = false,
```

You could then use this via:
```lua
require("git-worktree").setup({
    update_on_change_command = ":Telescope git_files",  -- ":Dirvish", etc.
})
```

If we go with this we can even remove `path` as an input argument to `on_tree_change_handler` although this may be needed again in the future.. :thinking:

**Comment by ThePrimeagen** [comment]
Sorry that I have not looked at this, I've been at a funeral.

I'll be back in action tomorrow.

**Comment by TamaMcGlinn** [comment]
Oh, pretty please, make the default 'Explore' not 'Ex' which is ambiguous if you have e.g. Extradite plugin installed.

**Comment by ThePrimeagen** [comment]
@TamaMcGlinn great feedback.

**Comment by ThePrimeagen** [comment]
This overall looks correct.  The only issue is that #29 has it so that we are using "e .".  Does `e .` work with Divrish?  Or does it still try to kick off netrw?

**Comment by mrossinek** [comment]
> Does `e .` work with Divrish? Or does it still try to kick off netrw?

Running a quick test shows that `e .` respect dirvish even if netrw is not explicitly disabled. I assume this is true for other file explorer plugins, too. But I have not tested that.

Nonetheless, I still see benefit for a configuration option in order to allow custom commands like `:Telescope git_files` (as proposed above). The default could obviously be `e .` though :+1: 

If you would accept such a PR I will gladly open one :+1:
