### ISSUE TITLE
Telescope bug

### ISSUE THREAD

**Issue by polarmutex** [ThePrimeagen/git-worktree.nvim#35]
apparently i did not fully test the telescope integration with my last PR, it it not showing any worktrees when opening in a bare repo, will look into it

**Comment by ThePrimeagen** [comment]
Mine works.

I get branches and all on latest.  I was able to create, delete, and switch.

@rudotriton did a great job with a PR in progress for harpoon.  We should probably add the same thing to this project.

https://github.com/ThePrimeagen/harpoon/pull/65

**Comment by polarmutex** [comment]
my cwd is being set to the directory above the folder I am opening neovim in. so I think this is an issue with my config, but will they open till I prove it

**Comment by ThePrimeagen** [comment]
I was able to open vim in a sub tree, create a new tree, and also switch tree.

**Comment by polarmutex** [comment]
found another plugin not respecting bare repos
