### ISSUE TITLE
Can't use "/" inside of the name of the branch

### ISSUE THREAD

**Issue by Matthieu-OD** [ThePrimeagen/git-worktree.nvim#61]
If I use a "/" inside of the name of the branch. Let's say I want to create or add a "fix/something" it will create a first folder named "fix" and inside of this folder a second one named "something" and the branch will be named "something" not "fix/something"

**Comment by polarmutex** [comment]
can you post more details on the steps you are doing to recreate this? this plugin is working for me with `/` in branch names

**Comment by Matthieu-OD** [comment]
my bad I found a solution (just change the path of the branch to a name without "/")

Thank's for your answer
