### ISSUE TITLE
Confirm deletions in telescope

### ISSUE THREAD

**Issue by brandoncc** [ThePrimeagen/git-worktree.nvim#63]
I'd like to have to confirm deletions in telescope so I can have a chance to rethink if I am deleting the wrong worktree. Is there an easy way to achieve that built in?

**Comment by polarmutex** [comment]
yes, I added it to the harpoon telescope plugin for deleting marks.

**Comment by brandoncc** [comment]
Thanks @polarmutex. I wasn't sure if there was a way to hook into the deletion without a PR. I created [a PR](https://github.com/ThePrimeagen/git-worktree.nvim/pull/68) for this feature.
