### ISSUE TITLE
Execute commands on Worktree changes

### ISSUE THREAD

**Issue by luiskunz** [ThePrimeagen/git-worktree.nvim#90]
Hello there

I've been trying how to execute custom commands when worktree changes, the docs say that this is possible using `Worktree.on_tree_change`, I'm not that expert in these configurations, where do I have to add these functions? I believe I'll need to create a Lua file and import it from the init.vim?

If somebody has already done something similar, will be amazing to have an example with the paths used!

Thank you so much and have an amazing day!

**Comment by tobias-z** [comment]
Hello @luiskunz 
I don't know if you have been able to fix this by now, but you could from your init.vim do the following
```
lua << EOF
require("luiskunz.git_worktree")
EOF
```

Then in the same directory as your `init.vim` create a folder called `lua` and a folder called `luiskunz` inside that (this makes sure that you wont ever collide with other plugin names when importing)

Inside the luiskunz folder create your `git_worktree.lua` file with whatever config you want.

```lua
-- git_worktree.lua
local Worktree = require("git-worktree")

Worktree.on_tree_change(function(op, metadata)
    print("tree changed!")
end)
```

If you are interested in learning more about using lua in your nvim config i would suggest reading this [nvim lua guide](https://github.com/nanotee/nvim-lua-guide)

Hope this helps :pray:

**Comment by luiskunz** [comment]
That did the job perfectly fine, thank you so much Tobias for the great solution and extra pieces of information!

For more than 4 weeks I had to do things manually after creating the worktree, this is just priceless.

All the best 🙌🏼 
Luis
